/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.Technician;

import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Arrays;
import utils.CSVParser;
import utils.ReadInfo;
import utils.Technician;

/**
 *
 * @author Preston
 */
public class TechnicianAppointmentView extends javax.swing.JFrame {
    
    private String appointmentID;
    private String managerID;
    private String manager;
    private String userID;
    private String user;
    private String technicianID;
    private String technician;
    private String userContext;
    private String timeSubmitted;
    private String status;
    private String requestCompletionTime;
    private String userComment;
    private String receiptID;
    private String receiptAppointmentID;
    private String userFeedback;
    private String paymentStatus;
    private String paymentTime;
    private String paymentMade;
    private String technicianComment;
    
    private DateTimeFormatter formatter = DateTimeFormatter.ofPattern("EEEE d MMMM uuuu");
    
    private Technician tech;

    /**
     * Creates new form TechnicianAppointmentView
     */
    public TechnicianAppointmentView(int rowSelector, Technician tech) {
        this.tech = tech;
        System.out.println("Technician object in AppointmentView constructor: " + this.tech);
        initComponents();
        
        String[] rowData = getAppointmentRow(rowSelector);
        
        String appointmentID = rowData[0];
        String managerID = rowData[1];
        String manager = ReadInfo.getUserByID(managerID, "manager");
        String userID = rowData[2];
        String user = ReadInfo.getUserByID(userID, "user");
        String technicianID = rowData[3];
        String technician = ReadInfo.getUserByID(technicianID, "technician");
        String userContext = rowData[4];
        String timeSubmitted = rowData[5];
        String status = rowData[6];
        String requestCompletionTime = rowData[7];
        String userComment = rowData[8];
        
        String[] rowDataReceipt = getReceiptRow(appointmentID);
        
        // The following variables are to be retrieved from another file.
        String receiptID = rowDataReceipt[0];
        String receiptAppointmentID = rowDataReceipt[1];
        String userFeedback = rowDataReceipt[2];
        String paymentStatus = rowDataReceipt[3];
        String paymentTime = rowDataReceipt[4];
        String paymentMade = rowDataReceipt[5];
        String technicianComment = rowDataReceipt[6];

        
        jLabelAppointmentID.setText(appointmentID);
        jLabelTime.setText(timeSubmitted);
        jLabelUser.setText(user);
        jLabelTechnician.setText(technician);
        jLabelManager.setText(manager);
        jLabelStatus.setText(status);
        jLabelReceiptID.setText(receiptID);
        
        
        
        
//        if (!paymentTime.equals("NULL")) {
//            System.out.println("Payment Time: " + paymentTime);
//            btnAppointmentCompleted.setVisible(false);
//            jLabelAppointmentCompletionTime.setText("Hi!");
//        }
        
        jLabelUserPaymentStatus.setText(paymentStatus);
        jLabelUserPaymentTime.setText(paymentTime);
        jLabelAppointmentCompletionTime.setText(requestCompletionTime);
        
        textareaUser.setText(userContext);
        textareaUserComment.setText(userComment);
        textareaUserFeedback.setText(userFeedback);
        textareaTechnicianComment.setText(technicianComment);
        textareaUser.setEditable(false);
        textareaUserComment.setEditable(false);
        textareaUserFeedback.setEditable(false);
        
        if (paymentStatus.equals("COMPLETED")) {
            textfieldRM.setText(paymentMade);
            textfieldRM.setEditable(false);
            btnPaymentConfirmation.setVisible(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textareaUser = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textareaUserComment = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textareaUserFeedback = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        textareaTechnicianComment = new javax.swing.JTextArea();
        btnReturn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        textfieldRM = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        btnPaymentConfirmation = new javax.swing.JButton();
        jLabelAppointmentID = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jLabelManager = new javax.swing.JLabel();
        jLabelTechnician = new javax.swing.JLabel();
        jLabelTime = new javax.swing.JLabel();
        jLabelUserPaymentStatus = new javax.swing.JLabel();
        jLabelUserPaymentTime = new javax.swing.JLabel();
        jLabelAppointmentCompletionTime = new javax.swing.JLabel();
        btnAppointmentCompleted = new javax.swing.JButton();
        jLabelStatus = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelReceiptID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("AppointmentID:");

        jLabel2.setText("Assigned by:");

        jLabel3.setText("Assigned to:");

        jLabel4.setText("Customer:");

        jLabel5.setText("User Problem:");

        textareaUser.setColumns(20);
        textareaUser.setRows(5);
        jScrollPane1.setViewportView(textareaUser);

        jLabel6.setText("Time Submitted:");

        jLabel8.setText("Status:");

        jLabel9.setText("Completion time:");

        jLabel10.setText("User comment:");

        textareaUserComment.setColumns(20);
        textareaUserComment.setRows(5);
        jScrollPane2.setViewportView(textareaUserComment);

        jLabel11.setText("User feedback:");

        textareaUserFeedback.setColumns(20);
        textareaUserFeedback.setRows(5);
        jScrollPane3.setViewportView(textareaUserFeedback);

        jLabel12.setText("Technician comment:");

        textareaTechnicianComment.setColumns(20);
        textareaTechnicianComment.setRows(5);
        jScrollPane4.setViewportView(textareaTechnicianComment);

        btnReturn.setText("Save and Return");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        jLabel14.setText("Payment status:");

        jLabel15.setText("Payment date:");

        jLabel16.setText("Payment made:");

        textfieldRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldRMActionPerformed(evt);
            }
        });

        jLabel17.setText("RM");

        btnPaymentConfirmation.setText("Confirm");
        btnPaymentConfirmation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentConfirmationActionPerformed(evt);
            }
        });

        jLabelAppointmentID.setText("jLabel13");
        jLabelAppointmentID.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jLabelAppointmentIDComponentShown(evt);
            }
        });

        jLabelUser.setText("jLabel18");

        jLabelManager.setText("jLabel19");

        jLabelTechnician.setText("jLabel20");

        jLabelTime.setText("jLabel21");

        jLabelUserPaymentStatus.setText("jLabel7");

        jLabelUserPaymentTime.setText("jLabel13");

        jLabelAppointmentCompletionTime.setText("jLabel18");

        btnAppointmentCompleted.setText("Mark as Completed");
        btnAppointmentCompleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppointmentCompletedActionPerformed(evt);
            }
        });

        jLabelStatus.setText("jLabel7");

        jLabel7.setText("ReceiptID:");

        jLabelReceiptID.setText("jLabel13");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelAppointmentCompletionTime)
                        .addGap(18, 18, 18)
                        .addComponent(btnAppointmentCompleted))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(286, 286, 286)
                        .addComponent(jLabel11))
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelUserPaymentStatus)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelUserPaymentTime, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfieldRM, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPaymentConfirmation))
                    .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelAppointmentID))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelTime)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelReceiptID)
                                .addGap(228, 228, 228)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelStatus))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelUser)
                                .addGap(53, 53, 53)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelManager)
                                .addGap(81, 81, 81)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelTechnician)))))
                .addGap(0, 101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabelAppointmentID)
                    .addComponent(jLabelUser)
                    .addComponent(jLabelManager)
                    .addComponent(jLabelTechnician))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabelTime)
                    .addComponent(jLabelStatus)
                    .addComponent(jLabel7)
                    .addComponent(jLabelReceiptID))
                .addGap(54, 54, 54)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(44, 44, 44)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(textfieldRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(btnPaymentConfirmation)
                    .addComponent(jLabelUserPaymentStatus)
                    .addComponent(jLabelUserPaymentTime))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(btnReturn)
                    .addComponent(jLabelAppointmentCompletionTime)
                    .addComponent(btnAppointmentCompleted))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
        
//        String strtextareaUser = textareaUser.getText();
//        String strtextareaUserComment = textareaUserComment.getText();
//        String strtextareaUserFeedback = textareaUserFeedback.getText();
        String strtextareaTechnicianComment = textareaTechnicianComment.getText(); // Receipt.txt
        String strtextfieldRM = textfieldRM.getText(); // Receipt.txt
        
        // Appointment updates:
        
        // Request completion date, request status
        
        // Receipt updates:
        LocalDateTime now = LocalDateTime.now();
        String formattedDateTime = formatter.format(now);
        
        Technician.updateReceipt("data/receipt.txt", jLabelReceiptID.getText(), jLabelAppointmentID.getText(), userFeedback, jLabelUserPaymentStatus.getText(), formattedDateTime, textfieldRM.getText(), textareaTechnicianComment.getText());
        
        new TechnicianHomePage(this.tech).setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnPaymentConfirmationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentConfirmationActionPerformed
        // TODO add your handling code here:
        String RMAmount = textfieldRM.getText();
        textfieldRM.setText(RMAmount);
        textfieldRM.setEditable(false);
        // To-Do: Add function to call technician object and update the technician file.
        LocalDateTime now = LocalDateTime.now();
        String formattedDateTime = formatter.format(now);
        
        
        
        jLabelUserPaymentStatus.setText("COMPLETED");
        jLabelUserPaymentTime.setText(formattedDateTime);
        jLabelUserPaymentStatus.setText("COMPLETED");
        btnPaymentConfirmation.setVisible(false);
        
        
        
    }//GEN-LAST:event_btnPaymentConfirmationActionPerformed

    private void jLabelAppointmentIDComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabelAppointmentIDComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelAppointmentIDComponentShown

    private void textfieldRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldRMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldRMActionPerformed

    private void btnAppointmentCompletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppointmentCompletedActionPerformed
        // TODO add your handling code here:
        LocalDateTime now = LocalDateTime.now();
        String formattedDateTime = formatter.format(now);
        jLabelAppointmentCompletionTime.setText(formattedDateTime);
        jLabelStatus.setText("COMPLETED");
        
        Technician.updateAppointment(jLabelAppointmentID.getText(), "COMPLETED");
        
        btnAppointmentCompleted.setVisible(false);
        
        
        
        // To-Do: Add code to update the data file. Maybe through the technician object.
    }//GEN-LAST:event_btnAppointmentCompletedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TechnicianAppointmentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TechnicianAppointmentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TechnicianAppointmentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TechnicianAppointmentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new TechnicianAppointmentView().setVisible(true);
            }
        });
    }
    
    public static String[] getAppointmentRow(int selectedRow) {
        String[][] appointmentData = ReadInfo.getData(9, "0,1,2,3,4,5,6,7,8", "data/appointment.txt");
        
        return appointmentData[selectedRow];
    }
    
    public static String[] getReceiptRow(String appointmentID) {
        String[][] receiptData = ReadInfo.getData(7, "0,1,2,3,4,5,6", "data/receipt.txt");
        String [] receiptDataRow = null;
        
        for (String[] receiptRow : receiptData) {
            if (receiptRow[1].equals(appointmentID)) {
                receiptDataRow = receiptRow;
            }
        }
        
        return receiptDataRow;
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAppointmentCompleted;
    private javax.swing.JButton btnPaymentConfirmation;
    private javax.swing.JButton btnReturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAppointmentCompletionTime;
    private javax.swing.JLabel jLabelAppointmentID;
    private javax.swing.JLabel jLabelManager;
    private javax.swing.JLabel jLabelReceiptID;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelTechnician;
    private javax.swing.JLabel jLabelTime;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JLabel jLabelUserPaymentStatus;
    private javax.swing.JLabel jLabelUserPaymentTime;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea textareaTechnicianComment;
    private javax.swing.JTextArea textareaUser;
    private javax.swing.JTextArea textareaUserComment;
    private javax.swing.JTextArea textareaUserFeedback;
    private javax.swing.JTextField textfieldRM;
    // End of variables declaration//GEN-END:variables
}
